# Python Libraries
     - numpy
     - pandas
     - matplotlib

# Data Science
     - Organizing, processing, analysing the huge amount of data
     - Applying data visualization
     - Extracting the data from the source
     - We have 20 python libraries for data science

# numpy
    - Numpy means numerical python
    - It is a fundamental package for scientific computing in python
    - numpy the python library
    -  It is used to create multi dimentional array for fast operation
# How to intall numpy
    - pip install numpy

# use the following import conversion to access numpy library
    - import numpy

In [4]:
import numpy as np

In [2]:
# 1 dimentional array
array1d = np.array([1,2,3,4,5])
print(array1d)
print(type(array1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
# checking numpy version
print(np.__version__)

1.26.4


In [15]:
# 0-d array
a = np.array(23)
print(a)

23


In [17]:
# conversion of list to array
li = [4,5,7,'a','p']
print(li,type(li))
ar = np.array(li)
print(ar,type(ar))

[4, 5, 7, 'a', 'p'] <class 'list'>
['4' '5' '7' 'a' 'p'] <class 'numpy.ndarray'>


In [18]:
# 3-d array
array3d = np.array([[[1,2,3,],[4,5,6]],[[6,7,8],[5,7,3]]])
print(array3d)
print(type(array3d))

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [5 7 3]]]
<class 'numpy.ndarray'>


In [25]:
# bultin function in numpy
print(array1d.dtype)
print(array1d.shape)
print(array1d.size)
print(array1d.ndim)
print(array3d.ndim)

int32
(5,)
5
1
3


In [26]:
print(dir(np),end = ' ')

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [28]:
# using range() function
a = np.array(range(10))
print(a)
print(a.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [34]:
b = np.array(range(1,20,2))
print(b)
print(b.ndim)

[ 1  3  5  7  9 11 13 15 17 19]
1


In [35]:
# arange()
a1 = np.arange(1,10)
print(a1)

[1 2 3 4 5 6 7 8 9]


In [36]:
b1 = np.arange(1,20,3)
print(b1)

[ 1  4  7 10 13 16 19]


In [39]:
# using arange() function we can store float values also
c1 = np.arange(1.5,10.5)
print(c1)

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [43]:
# reshape()
x = np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [45]:
# one's method
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# one's method
a = np.ones((3,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
# zero's method
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# zero's method
b = np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
# full()
a = np.full((4,4),7)
a

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [54]:
# print diagnal
np.diag(a)

array([7, 7, 7, 7])

In [55]:
# full()
a = np.full((4,4),'d')
a

array([['d', 'd', 'd', 'd'],
       ['d', 'd', 'd', 'd'],
       ['d', 'd', 'd', 'd'],
       ['d', 'd', 'd', 'd']], dtype='<U1')

In [57]:
# random()
r = np.random.randint(1,30)
r

21

In [60]:
s = np.random.randint(1,20,12).reshape(3,4)
s

array([[11,  9, 13,  9],
       [ 8, 17, 13,  2],
       [ 6,  7,  4, 19]])

In [63]:
p = np.random.random((6)).reshape(2,3)
p

array([[0.125001  , 0.32605348, 0.77517122],
       [0.32426141, 0.89488233, 0.25426931]])

In [64]:
# randn
f = np.random.randn(2,3)
f

array([[ 0.12702852,  1.14278289, -1.18831016],
       [-1.8443557 , -1.29954789, -1.49341562]])

In [68]:
a = np.random.randint(1,30,(10,3))
a

array([[15, 18,  5],
       [ 1, 12, 17],
       [28, 24, 25],
       [15, 17, 26],
       [ 5, 18, 20],
       [ 8,  7, 13],
       [ 9, 15,  6],
       [24, 16, 16],
       [23,  5,  4],
       [ 4, 29, 20]])

In [69]:
a[1:5]

array([[ 1, 12, 17],
       [28, 24, 25],
       [15, 17, 26],
       [ 5, 18, 20]])

In [70]:
a[5:]

array([[ 8,  7, 13],
       [ 9, 15,  6],
       [24, 16, 16],
       [23,  5,  4],
       [ 4, 29, 20]])

In [71]:
a[1::2]

array([[ 1, 12, 17],
       [15, 17, 26],
       [ 8,  7, 13],
       [24, 16, 16],
       [ 4, 29, 20]])

In [73]:
a[::-1] # recere the index

array([[ 4, 29, 20],
       [23,  5,  4],
       [24, 16, 16],
       [ 9, 15,  6],
       [ 8,  7, 13],
       [ 5, 18, 20],
       [15, 17, 26],
       [28, 24, 25],
       [ 1, 12, 17],
       [15, 18,  5]])

In [74]:
a[1::3]

array([[ 1, 12, 17],
       [ 5, 18, 20],
       [24, 16, 16]])

In [75]:
print(a>5)

[[ True  True False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False False]
 [False  True  True]]


In [76]:
print(a<5)

[[False False False]
 [ True False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False  True]
 [ True False False]]


In [77]:
a[a>5]

array([15, 18, 12, 17, 28, 24, 25, 15, 17, 26, 18, 20,  8,  7, 13,  9, 15,
        6, 24, 16, 16, 23, 29, 20])

In [78]:
a[a<5]

array([1, 4, 4])

In [79]:
# print max and min values in matrix
print(a.max())
print(a.min())

29
1


In [80]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [83]:
print(a+b) # matrix addition

[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [84]:
print(a-b) # marix substraction

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [85]:
print(a%b) # matrix modules

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [86]:
# matrix multipication using dot method
# rule :- 1st colums = 2nd matrix rows

In [87]:
a.dot(b)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [88]:
b.dot(a)

array([[105, 138, 171],
       [132, 174, 216],
       [159, 210, 261]])

In [90]:
print(np.mean(a))
print(np.median(a))

4.0
4.0


In [91]:
print(a+3)
print(b+5)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[15 16 17]
 [18 19 20]
 [21 22 23]]


In [92]:
np.log(2)

0.6931471805599453

In [93]:
np.log(10)

2.302585092994046

In [94]:
np.log([4,6,7,8,9])

array([1.38629436, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [95]:
np.exp(4)

54.598150033144236

In [96]:
np.exp(3)

20.085536923187668

In [97]:
np.exp([3,7,8,1,2,6])

array([2.00855369e+01, 1.09663316e+03, 2.98095799e+03, 2.71828183e+00,
       7.38905610e+00, 4.03428793e+02])

In [98]:
np.sin(0)

0.0

In [99]:
np.cos(45)

0.5253219888177297

In [100]:
np.tan(0)

0.0

# references
    w3 schools.com
    javatpoint.com
    greeksforgreeks.com